spring:
  data:
    mongodb:
      uri: mongodb://localhost/Pizzas
      port: 27017
      username:
      password:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG